[build]
  command = "touch proto.json && yarn && yarn build"
  publish = "./build"

[build.environment]
  NETLIFY_USE_YARN = "true"
  PYTHON_VERSION = "3.8"
  YARN_VERSION = "1.22.10"

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 301
